"""Initial schema

Revision ID: b648752192e5
Revises: 
Create Date: 2025-11-27 11:10:35.939460

"""
from typing import Sequence, Union

from alembic import op  # type: ignore[import-not-found]
import sqlalchemy as sa  # type: ignore[import-not-found]


# revision identifiers, used by Alembic.
revision: str = 'b648752192e5'  # type: ignore[assignment]
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('samples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sample_id', sa.String(length=255), nullable=False),
    sa.Column('biological_sample_id', sa.String(length=100), nullable=False),
    sa.Column('treatment', sa.String(length=50), nullable=False),
    sa.Column('concentration_ug', sa.Float(), nullable=True),
    sa.Column('preparation_method', sa.String(length=50), nullable=True),
    sa.Column('passage_number', sa.Integer(), nullable=True),
    sa.Column('fraction_number', sa.Integer(), nullable=True),
    sa.Column('experiment_date', sa.DateTime(), nullable=True),
    sa.Column('upload_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('processing_status', sa.String(length=20), nullable=False),
    sa.Column('qc_status', sa.String(length=20), nullable=True),
    sa.Column('file_path_fcs', sa.Text(), nullable=True),
    sa.Column('file_path_nta', sa.Text(), nullable=True),
    sa.Column('file_path_tem', sa.Text(), nullable=True),
    sa.Column('operator', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sample_status', 'samples', ['processing_status', 'qc_status'], unique=False)
    op.create_index('idx_sample_treatment_date', 'samples', ['treatment', 'experiment_date'], unique=False)
    op.create_index(op.f('ix_samples_biological_sample_id'), 'samples', ['biological_sample_id'], unique=False)
    op.create_index(op.f('ix_samples_processing_status'), 'samples', ['processing_status'], unique=False)
    op.create_index(op.f('ix_samples_qc_status'), 'samples', ['qc_status'], unique=False)
    op.create_index(op.f('ix_samples_sample_id'), 'samples', ['sample_id'], unique=True)
    op.create_index(op.f('ix_samples_treatment'), 'samples', ['treatment'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('fcs_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.Column('total_events', sa.Integer(), nullable=False),
    sa.Column('fsc_mean', sa.Float(), nullable=True),
    sa.Column('fsc_median', sa.Float(), nullable=True),
    sa.Column('fsc_std', sa.Float(), nullable=True),
    sa.Column('fsc_cv', sa.Float(), nullable=True),
    sa.Column('ssc_mean', sa.Float(), nullable=True),
    sa.Column('ssc_median', sa.Float(), nullable=True),
    sa.Column('ssc_std', sa.Float(), nullable=True),
    sa.Column('ssc_cv', sa.Float(), nullable=True),
    sa.Column('particle_size_mean_nm', sa.Float(), nullable=True),
    sa.Column('particle_size_median_nm', sa.Float(), nullable=True),
    sa.Column('particle_size_std_nm', sa.Float(), nullable=True),
    sa.Column('particle_size_d10_nm', sa.Float(), nullable=True),
    sa.Column('particle_size_d90_nm', sa.Float(), nullable=True),
    sa.Column('cd9_positive_pct', sa.Float(), nullable=True),
    sa.Column('cd81_positive_pct', sa.Float(), nullable=True),
    sa.Column('cd63_positive_pct', sa.Float(), nullable=True),
    sa.Column('fluorescence_stats', sa.JSON(), nullable=True),
    sa.Column('debris_pct', sa.Float(), nullable=True),
    sa.Column('doublets_pct', sa.Float(), nullable=True),
    sa.Column('parquet_file_path', sa.Text(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fcs_results_sample_id'), 'fcs_results', ['sample_id'], unique=False)
    op.create_table('nta_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.Column('mean_size_nm', sa.Float(), nullable=False),
    sa.Column('median_size_nm', sa.Float(), nullable=False),
    sa.Column('mode_size_nm', sa.Float(), nullable=True),
    sa.Column('d10_nm', sa.Float(), nullable=True),
    sa.Column('d50_nm', sa.Float(), nullable=True),
    sa.Column('d90_nm', sa.Float(), nullable=True),
    sa.Column('std_dev_nm', sa.Float(), nullable=True),
    sa.Column('concentration_particles_ml', sa.Float(), nullable=True),
    sa.Column('concentration_particles_ml_error', sa.Float(), nullable=True),
    sa.Column('bin_30_50nm_pct', sa.Float(), nullable=True),
    sa.Column('bin_50_80nm_pct', sa.Float(), nullable=True),
    sa.Column('bin_80_100nm_pct', sa.Float(), nullable=True),
    sa.Column('bin_100_120nm_pct', sa.Float(), nullable=True),
    sa.Column('bin_120_150nm_pct', sa.Float(), nullable=True),
    sa.Column('bin_150_200nm_pct', sa.Float(), nullable=True),
    sa.Column('temperature_celsius', sa.Float(), nullable=True),
    sa.Column('ph', sa.Float(), nullable=True),
    sa.Column('conductivity', sa.Float(), nullable=True),
    sa.Column('parquet_file_path', sa.Text(), nullable=False),
    sa.Column('measurement_date', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nta_results_sample_id'), 'nta_results', ['sample_id'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=100), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=True),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('current_step', sa.String(length=255), nullable=True),
    sa.Column('result_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_traceback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_job_status_created', 'processing_jobs', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_processing_jobs_job_id'), 'processing_jobs', ['job_id'], unique=True)
    op.create_index(op.f('ix_processing_jobs_job_type'), 'processing_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_processing_jobs_sample_id'), 'processing_jobs', ['sample_id'], unique=False)
    op.create_index(op.f('ix_processing_jobs_status'), 'processing_jobs', ['status'], unique=False)
    op.create_table('qc_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.Column('instrument_type', sa.String(length=20), nullable=False),
    sa.Column('qc_status', sa.String(length=20), nullable=False),
    sa.Column('checks_performed', sa.JSON(), nullable=False),
    sa.Column('checks_passed', sa.JSON(), nullable=False),
    sa.Column('checks_failed', sa.JSON(), nullable=False),
    sa.Column('checks_warnings', sa.JSON(), nullable=True),
    sa.Column('qc_flags', sa.Text(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_qc_instrument_status', 'qc_reports', ['instrument_type', 'qc_status'], unique=False)
    op.create_index(op.f('ix_qc_reports_instrument_type'), 'qc_reports', ['instrument_type'], unique=False)
    op.create_index(op.f('ix_qc_reports_qc_status'), 'qc_reports', ['qc_status'], unique=False)
    op.create_index(op.f('ix_qc_reports_sample_id'), 'qc_reports', ['sample_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qc_reports_sample_id'), table_name='qc_reports')
    op.drop_index(op.f('ix_qc_reports_qc_status'), table_name='qc_reports')
    op.drop_index(op.f('ix_qc_reports_instrument_type'), table_name='qc_reports')
    op.drop_index('idx_qc_instrument_status', table_name='qc_reports')
    op.drop_table('qc_reports')
    op.drop_index(op.f('ix_processing_jobs_status'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_sample_id'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_job_type'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_job_id'), table_name='processing_jobs')
    op.drop_index('idx_job_status_created', table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index(op.f('ix_nta_results_sample_id'), table_name='nta_results')
    op.drop_table('nta_results')
    op.drop_index(op.f('ix_fcs_results_sample_id'), table_name='fcs_results')
    op.drop_table('fcs_results')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_samples_treatment'), table_name='samples')
    op.drop_index(op.f('ix_samples_sample_id'), table_name='samples')
    op.drop_index(op.f('ix_samples_qc_status'), table_name='samples')
    op.drop_index(op.f('ix_samples_processing_status'), table_name='samples')
    op.drop_index(op.f('ix_samples_biological_sample_id'), table_name='samples')
    op.drop_index('idx_sample_treatment_date', table_name='samples')
    op.drop_index('idx_sample_status', table_name='samples')
    op.drop_table('samples')
    # ### end Alembic commands ###
